### ISSUE TITLE
Switching a factor does nothing under some circumstances

### ISSUE THREAD

**Issue by Gordon-Dry** [lolluslollus/lollo_town_tuning_1#1]
I started a game with "Person capacity factor" set to **+** and later I decided to set it back to **0**.
But nothing happened. Even no freeze.
But as soon as I chose to set it to **-** it seemed to work as the game shortly froze.
And afterwards setting it to **0** also seemed to work as the game shortly froze.
Only the initial attempt to change it from **+** to **0** did not make the game freeze.

But then ... closing the Town tuning UI and opening it again I see that nothing changed.
[stdout.zip](https://github.com/lolluslollus/lollo_town_tuning_1/files/11062794/stdout.zip)

I did some more tests inclusing the other 2 factor settings and this is the result:

- a change from **+** to **0** does _not_ work _and_ shows no freeze
- a change from **-** to **0** does _not_ work _and_ shows no freeze
- a change from **+** to **-** does _not_ work _but_ shows a freeze
- a change from **-** to **+** does _not_ work _but_ shows a freeze
but
- a change from **+** to **--** does work
- a change from **-** to **++** does work
- a change from **++** to **0** does work
- a change from **--** to **0** does work

^why does the bold - looks like the normal - ?

**Comment by Gordon-Dry** [comment]
Wait...
I changed "Person capacity factor" to **++** which worked.
Then I set it to **0** which did a freeze, but it was changed to **+**

There is a serious bug in there.

**Comment by Gordon-Dry** [comment]
It seems to make a difference for the kind of weirdness if the game is paused or not.

But whatsoever I cannot set "Person capacity factor" to **0** **_under any circumstance_**.

**Comment by Gordon-Dry** [comment]
Well, now I rebooted the game, loaded the save, let it run for a minute and was able to change the values.
Could it be that trying to change those values shortly after loading the game - especially when the game is paused - could trigger that issue?

**Comment by lolluslollus** [comment]
This should not happen anymore, since I disable the UI during those expensive changes.
